name: GraphRAG Build Nightly

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  SHA: ${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{steps.get-image.outputs.IMAGE}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
        password: ${{ secrets.PUBLIC_DOCKERHUB_TOKEN }}
    
    - name: Get Image tag
      id: get-image
      run: |
        IMAGE=tigergraph/graphrag:${SHA::6}
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT${{ needs.setup.outputs.image }} 
 
    - name: Build and push Docker image GraphRAG
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./graphrag/Dockerfile
        push: true
        tags: |
           ${{ env.IMAGE }}
           tigergraph/graphrag:dev
 
    - name: Build and push Docker image ECC
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ecc/Dockerfile
        push: true
        tags: |
           ${{ env.IMAGE }}
           tigergraph/graphrag-ecc:dev

    - name: Build and push Docker image chat-history
      uses: docker/build-push-action@v5
      with:
        context: chat-history/
        file: ./chat-history/Dockerfile
        push: true
        tags: |
           ${{ env.IMAGE }}
           tigergraph/chat-history:dev

    - name: Build and push Docker image graphrag-ui
      uses: docker/build-push-action@v5
      with:
        context: graphrag-ui/
        file: ./graphrag-ui/Dockerfile
        push: true
        tags: |
           ${{ env.IMAGE }}
           tigergraph/graphrag-ui:dev

    - name: Set SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

    - name: Update on-prem dev environment
      run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_ADDRESS }} << 'ENDSSH'
          cd graphrag
          docker compose pull
          docker compose up -d
          ENDSSH
