name: Run Pytest before merging to main

on:
  pull_request:
    branches:
      - main
      - dev
      - cloud-main
      - cloud-dev

jobs:
  test:
    runs-on: [ self-hosted, dind ]

    services:
      tigergraph:
        image: tigergraph/community:latest
        ports:
          - 9000:9000
          - 14240:14240

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Install and Check Python Setup
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r common/requirements.txt
          pip install pytest

      - name: Create db config
        run: |
          mkdir configs
          echo "$SERVER_CONFIG_OPENAI_GPT4" > configs/openai_gpt4_config.json
          echo "$SERVER_CONFIG_AZURE_GPT35" > configs/azure_server_config.json
          echo "$SERVER_CONFIG_OPENAI_GPT35" > configs/openai_gpt3.5-turbo_config.json
          echo "$SERVER_CONFIG_GCP_TEXT_BISON" > configs/gcp_text-bison_config.json
          echo "$GCP_CREDS_CONFIG" > configs/GCP_CREDS.json
          echo "$SERVER_TEST_EVALUATOR" > configs/test_evaluation_model_config.json
          echo "$SERVER_CONFIG_BEDROCK_CLAUDE3" > configs/bedrock_config.json
        env:
          DB_CONFIG: ${{ secrets.DB_CONFIG }}
          SERVER_CONFIG:  ${{ secrets.SERVER_CONFIG_OPENAI_GPT4 }}
          SERVER_CONFIG_OPENAI_GPT4:  ${{ secrets.SERVER_CONFIG_OPENAI_GPT4 }}
          SERVER_CONFIG_AZURE_GPT35: ${{ secrets.SERVER_CONFIG_AZURE_GPT35 }}
          SERVER_CONFIG_GCP_TEXT_BISON: ${{ secrets.SERVER_CONFIG_GCP_TEXT_BISON }}
          SERVER_CONFIG_OPENAI_GPT35: ${{ secrets.SERVER_CONFIG_OPENAI_GPT35 }}
          SERVER_CONFIG_BEDROCK_CLAUDE3: ${{ secrets.SERVER_CONFIG_BEDROCK_CLAUDE3 }}
          GCP_CREDS_CONFIG: ${{ secrets.GCP_CREDS_CONFIG }}
          SERVER_TEST_EVALUATOR: ${{ secrets.SERVER_TEST_EVALUATOR }}

      - name: Run pytest
        run: |
          source venv/bin/activate
          cp -r graphrag/tests/*test* graphrag/tests/create_wandb_report.py graphrag/app/ 
          cd graphrag/app
          python -m pytest --disable-warnings
        env:
          DB_CONFIG: ${{ secrets.DB_CONFIG }}
          SERVER_CONFIG:  ${{ secrets.SERVER_CONFIG_OPENAI_GPT4 }}
          SERVER_CONFIG_OPENAI_GPT4:  ${{ secrets.SERVER_CONFIG_OPENAI_GPT4 }}
          SERVER_CONFIG_AZURE_GPT35: ${{ secrets.SERVER_CONFIG_AZURE_GPT35 }}
          SERVER_CONFIG_GCP_TEXT_BISON: ${{ secrets.SERVER_CONFIG_GCP_TEXT_BISON }}
          SERVER_CONFIG_OPENAI_GPT35: ${{ secrets.SERVER_CONFIG_OPENAI_GPT35 }}
          SERVER_CONFIG_BEDROCK_CLAUDE3: ${{ secrets.SERVER_CONFIG_BEDROCK_CLAUDE3 }}
          GCP_CREDS_CONFIG: ${{ secrets.GCP_CREDS_CONFIG }}
          SERVER_TEST_EVALUATOR: ${{ secrets.SERVER_TEST_EVALUATOR }}
          PYTHONPATH: /opt/actions-runner/_work/GraphRAG/GraphRAG:/opt/actions-runner/_work/GraphRAG/GraphRAG/tests:/opt/actions-runner/_work/GraphRAG/GraphRAG/tests/app:/opt/actions-runner/_work/_tool/Python/3.11.8/x64/lib/python3.11/site-packages
      
